Consider the below code to answer further questions:

In [7]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [8]:
type(list_)

list

In [9]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [10]:
for i in list_:
    print(i,type(list_))
    

1 <class 'list'>
2 <class 'list'>
3 <class 'list'>
4 <class 'list'>
5 <class 'list'>


In [15]:
for i in array_list:
    print(i,type(i))

1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


Q3. Considering the following changes in the variable, array_list:

In [12]:
array_list = np.array(object = list_, dtype = int)

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [14]:
list_

['1', '2', '3', '4', '5']

Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_and array_list.


Yes, there will be a difference in the data types of the elements present in list_ and array_list. Initially, array_list is a NumPy array with string values (dtype='<U1'), and then it is converted to a new NumPy array with an integer data type (dtype=int).

To print the data types of each element in both variables, you can iterate over the elements and use the type()

This code will iterate over each element in list_ and array_list and print the data type of each element on separate lines.

Initially, the elements in list_ are strings since they are enclosed in quotes ('1', '2', '3', '4', '5'). After converting list_ to a NumPy array with dtype='<U1', the elements in array_list are also strings.

However, when array_list is converted to a new NumPy array with dtype=int, the elements are cast to integers. Therefore, the elements in the final array_list have a data type of int.

Keep in mind that during the conversion from strings to integers, if any of the elements in list_ cannot be converted to an integer, it will raise a ValueError.

In [16]:
for i in list_:
    print(i,type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [17]:
for i in array_list:
    print(i,type(array_list))

1 <class 'numpy.ndarray'>
2 <class 'numpy.ndarray'>
3 <class 'numpy.ndarray'>
4 <class 'numpy.ndarray'>
5 <class 'numpy.ndarray'>


Consider the below code to answer further questions:

In [18]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [19]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [20]:
num_array.shape

(2, 3)

In [21]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])